create table if not exists room
(
    room_id     SERIAL PRIMARY KEY,
    capacity    INT          NOT NULL,
    room_type   VARCHAR(128) NOT NULL,
    room_status VARCHAR(128) NOT NULL,
    path        VARCHAR(255),
    guest_id    BIGINT,
    FOREIGN KEY (guest_id) REFERENCES guest (guest_id),
    constraint room_room_status_check check (room_status in ('VACANT', 'OCCUPIED', 'RESERVED', 'MAINTENANCE')),
    constraint room_room_type_check check (room_type in
                                           ('SINGLE', 'DOUBLE', 'TRIPLE',
                                            'QUAD', 'QUEEN', 'KING', 'TWIN',
                                            'HOLLYWOOD', 'STUDIO', 'CABANA',
                                            'VILLA', 'PENTHOUSES', 'STANDARD',
                                            'DELUXE', 'JOINT', 'CONNECTING',
                                            'SUIT', 'APARTMENT', 'JUNIOR',
                                            'BRIDAL', 'HONEYMOON',
                                            'PRESIDENTIAL', 'ACCESSIBLE'))
);

INSERT INTO room (capacity, room_type, room_status, path, guest_id)
VALUES (2, 'SINGLE', 'RESERVED', 'https://raw.githubusercontent.com/Lokankara/Patterns/main/img/image_1.jpg', 1),
       (2, 'DOUBLE', 'OCCUPIED', 'https://raw.githubusercontent.com/Lokankara/Patterns/main/img/image_2.jpg', 1),
       (3, 'TRIPLE', 'RESERVED', 'https://raw.githubusercontent.com/Lokankara/Patterns/main/img/image_3.jpg', 2),
       (4, 'QUAD', 'OCCUPIED', 'https://raw.githubusercontent.com/Lokankara/Patterns/main/img/image_4.jpg', 4),
       (2, 'QUEEN', 'OCCUPIED', 'https://raw.githubusercontent.com/Lokankara/Patterns/main/img/image_5.jpg', 5),
       (2, 'KING', 'RESERVED', 'https://raw.githubusercontent.com/Lokankara/Patterns/main/img/image_6.jpg', 6),
       (2, 'TWIN', 'OCCUPIED', 'https://raw.githubusercontent.com/Lokankara/Patterns/main/img/image_7.jpg', 7),
       (2, 'HOLLYWOOD', 'RESERVED', 'https://raw.githubusercontent.com/Lokankara/Patterns/main/img/image_8.jpg', 8),
       (2, 'STUDIO', 'OCCUPIED', 'https://raw.githubusercontent.com/Lokankara/Patterns/main/img/image_9.jpg', 9),
       (2, 'CABANA', 'RESERVED', 'https://raw.githubusercontent.com/Lokankara/Patterns/main/img/image_10.jpg', 10),
       (4, 'VILLA', 'MAINTENANCE', 'https://raw.githubusercontent.com/Lokankara/Patterns/main/img/image_11.jpg', 11),
       (2, 'PENTHOUSES', 'VACANT', 'https://raw.githubusercontent.com/Lokankara/Patterns/main/img/image_12.jpg', 12),
       (2, 'STANDARD', 'MAINTENANCE', 'https://raw.githubusercontent.com/Lokankara/Patterns/main/img/image_13.jpg', 13),
       (2, 'DELUXE', 'VACANT', 'https://raw.githubusercontent.com/Lokankara/Patterns/main/img/image_14.jpg', 14),
       (4, 'JOINT', 'VACANT', 'https://raw.githubusercontent.com/Lokankara/Patterns/main/img/image_15.jpg', 15),
       (4, 'CONNECTING', 'MAINTENANCE', 'https://raw.githubusercontent.com/Lokankara/Patterns/main/img/image_16.jpg', 16),
       (2, 'SUIT', 'VACANT', 'https://raw.githubusercontent.com/Lokankara/Patterns/main/img/image_17.jpg', 17),
       (2, 'APARTMENT', 'MAINTENANCE', 'https://raw.githubusercontent.com/Lokankara/Patterns/main/img/image_18.jpg', 18),
       (2, 'JUNIOR', 'VACANT', 'https://raw.githubusercontent.com/Lokankara/Patterns/main/img/image_19.jpg', 19),
       (2, 'BRIDAL', 'VACANT', 'https://raw.githubusercontent.com/Lokankara/Patterns/main/img/image_20.jpg', 20),
       (2, 'HONEYMOON', 'MAINTENANCE', 'https://raw.githubusercontent.com/Lokankara/Patterns/main/img/image_21.jpg', 21),
       (2, 'PRESIDENTIAL', 'VACANT', 'https://raw.githubusercontent.com/Lokankara/Patterns/main/img/image_22.jpg', 22),
       (2, 'ACCESSIBLE', 'VACANT', 'https://raw.githubusercontent.com/Lokankara/Patterns/main/img/image_23.jpg', 23),
       (2, 'SINGLE', 'VACANT', 'https://raw.githubusercontent.com/Lokankara/Patterns/main/img/image_24.jpg', 24),
       (2, 'DOUBLE', 'VACANT', 'https://raw.githubusercontent.com/Lokankara/Patterns/main/img/image_25.jpg', 25),
       (3, 'TRIPLE', 'MAINTENANCE', 'https://raw.githubusercontent.com/Lokankara/Patterns/main/img/image_26.jpg', 26),
       (2, 'SINGLE', 'VACANT', 'https://raw.githubusercontent.com/Lokankara/Patterns/main/img/image_27.jpg', 27),
       (2, 'DOUBLE', 'MAINTENANCE', 'https://raw.githubusercontent.com/Lokankara/Patterns/main/img/image_28.jpg', 28),
       (3, 'TRIPLE', 'MAINTENANCE', 'https://raw.githubusercontent.com/Lokankara/Patterns/main/img/image_29.jpg', 29),
       (4, 'QUAD', 'VACANT', 'https://raw.githubusercontent.com/Lokankara/Patterns/main/img/image_30.jpg', 30),
       (2, 'QUEEN', 'VACANT', 'https://raw.githubusercontent.com/Lokankara/Patterns/main/img/image_31.jpg', 31),
       (2, 'KING', 'MAINTENANCE', 'https://raw.githubusercontent.com/Lokankara/Patterns/main/img/image_32.jpg', 32),
       (2, 'TWIN', 'VACANT', 'https://raw.githubusercontent.com/Lokankara/Patterns/main/img/image_33.jpg', 33),
       (2, 'HOLLYWOOD', 'VACANT', 'https://raw.githubusercontent.com/Lokankara/Patterns/main/img/image_34.jpg', 34),
       (2, 'STUDIO', 'MAINTENANCE', 'https://raw.githubusercontent.com/Lokankara/Patterns/main/img/image_35.jpg', 35),
       (2, 'CABANA', 'VACANT', 'https://raw.githubusercontent.com/Lokankara/Patterns/main/img/image_36.jpg', 36),
       (2, 'SUIT', 'VACANT', 'https://raw.githubusercontent.com/Lokankara/Patterns/main/img/image_37.jpg', 37),
       (2, 'APARTMENT', 'MAINTENANCE', 'https://raw.githubusercontent.com/Lokankara/Patterns/main/img/image_38.jpg', 38),
       (2, 'JUNIOR', 'VACANT', 'https://raw.githubusercontent.com/Lokankara/Patterns/main/img/image_39.jpg', 39),
       (2, 'BRIDAL', 'VACANT', 'https://raw.githubusercontent.com/Lokankara/Patterns/main/img/image_40.jpg', 40),
       (4, 'VILLA', 'MAINTENANCE', 'https://raw.githubusercontent.com/Lokankara/Patterns/main/img/image_41.jpg', 41),
       (2, 'PENTHOUSES', 'VACANT', 'https://raw.githubusercontent.com/Lokankara/Patterns/main/img/image_42.jpg', 42),
       (2, 'STANDARD', 'MAINTENANCE', 'https://raw.githubusercontent.com/Lokankara/Patterns/main/img/image_43.jpg', 43),
       (2, 'DELUXE', 'VACANT', 'https://raw.githubusercontent.com/Lokankara/Patterns/main/img/image_44.jpg', 44),
       (4, 'JOINT', 'VACANT', 'https://raw.githubusercontent.com/Lokankara/Patterns/main/img/image_45.jpg', 45),
       (4, 'CONNECTING', 'MAINTENANCE', 'https://raw.githubusercontent.com/Lokankara/Patterns/main/img/image_46.jpg', 46),
       (2, 'SUIT', 'VACANT', 'https://raw.githubusercontent.com/Lokankara/Patterns/main/img/image_47.jpg', 47),
       (2, 'APARTMENT', 'MAINTENANCE', 'https://raw.githubusercontent.com/Lokankara/Patterns/main/img/image_48.jpg', 48),
       (2, 'JUNIOR', 'VACANT', 'https://raw.githubusercontent.com/Lokankara/Patterns/main/img/image_49.jpg', 49),
       (2, 'BRIDAL', 'VACANT', 'https://raw.githubusercontent.com/Lokankara/Patterns/main/img/image_50.jpg', 51),
       (2, 'SINGLE', 'RESERVED', 'https://raw.githubusercontent.com/Lokankara/Patterns/main/img/image_101.jpg', 52),
       (2, 'DOUBLE', 'OCCUPIED', 'https://raw.githubusercontent.com/Lokankara/Patterns/main/img/image_102.jpg', 53),
       (3, 'TRIPLE', 'RESERVED', 'https://raw.githubusercontent.com/Lokankara/Patterns/main/img/image_103.jpg', 54),
       (4, 'QUAD', 'OCCUPIED', 'https://raw.githubusercontent.com/Lokankara/Patterns/main/img/image_104.jpg', 55),
       (2, 'QUEEN', 'OCCUPIED', 'https://raw.githubusercontent.com/Lokankara/Patterns/main/img/image_105.jpg', 56),
       (2, 'KING', 'RESERVED', 'https://raw.githubusercontent.com/Lokankara/Patterns/main/img/image_106.jpg', 57),
       (2, 'TWIN', 'OCCUPIED', 'https://raw.githubusercontent.com/Lokankara/Patterns/main/img/image_107.jpg', 58),
       (2, 'HOLLYWOOD', 'RESERVED', 'https://raw.githubusercontent.com/Lokankara/Patterns/main/img/image_108.jpg', 59),
       (2, 'STUDIO', 'OCCUPIED', 'https://raw.githubusercontent.com/Lokankara/Patterns/main/img/image_109.jpg', 59),
       (2, 'CABANA', 'RESERVED', 'https://raw.githubusercontent.com/Lokankara/Patterns/main/img/image_110.jpg', 60),
       (4, 'VILLA', 'MAINTENANCE', 'https://raw.githubusercontent.com/Lokankara/Patterns/main/img/image_111.jpg', 61),
       (2, 'PENTHOUSES', 'VACANT', 'https://raw.githubusercontent.com/Lokankara/Patterns/main/img/image_112.jpg', 62),
       (2, 'STANDARD', 'MAINTENANCE', 'https://raw.githubusercontent.com/Lokankara/Patterns/main/img/image_113.jpg', 63),
       (2, 'DELUXE', 'VACANT', 'https://raw.githubusercontent.com/Lokankara/Patterns/main/img/image_114.jpg', 64),
       (4, 'JOINT', 'VACANT', 'https://raw.githubusercontent.com/Lokankara/Patterns/main/img/image_115.jpg', 65),
       (4, 'CONNECTING', 'MAINTENANCE', 'https://raw.githubusercontent.com/Lokankara/Patterns/main/img/image_116.jpg', 66),
       (2, 'SUIT', 'VACANT', 'https://raw.githubusercontent.com/Lokankara/Patterns/main/img/image_117.jpg', 67),
       (2, 'APARTMENT', 'MAINTENANCE', 'https://raw.githubusercontent.com/Lokankara/Patterns/main/img/image_118.jpg', 68),
       (2, 'JUNIOR', 'VACANT', 'https://raw.githubusercontent.com/Lokankara/Patterns/main/img/image_119.jpg', 69),
       (2, 'BRIDAL', 'VACANT', 'https://raw.githubusercontent.com/Lokankara/Patterns/main/img/image_120.jpg', 70),
       (2, 'HONEYMOON', 'MAINTENANCE', 'https://raw.githubusercontent.com/Lokankara/Patterns/main/img/image_121.jpg', 71),
       (2, 'PRESIDENTIAL', 'VACANT', 'https://raw.githubusercontent.com/Lokankara/Patterns/main/img/image_122.jpg', 72),
       (2, 'ACCESSIBLE', 'VACANT', 'https://raw.githubusercontent.com/Lokankara/Patterns/main/img/image_123.jpg', 73),
       (2, 'SINGLE', 'VACANT', 'https://raw.githubusercontent.com/Lokankara/Patterns/main/img/image_124.jpg', 74),
       (2, 'DOUBLE', 'VACANT', 'https://raw.githubusercontent.com/Lokankara/Patterns/main/img/image_125.jpg', 75),
       (3, 'TRIPLE', 'MAINTENANCE', 'https://raw.githubusercontent.com/Lokankara/Patterns/main/img/image_126.jpg', 76),
       (2, 'SINGLE', 'VACANT', 'https://raw.githubusercontent.com/Lokankara/Patterns/main/img/image_127.jpg', 77),
       (2, 'DOUBLE', 'MAINTENANCE', 'https://raw.githubusercontent.com/Lokankara/Patterns/main/img/image_128.jpg', 78),
       (3, 'TRIPLE', 'MAINTENANCE', 'https://raw.githubusercontent.com/Lokankara/Patterns/main/img/image_129.jpg', 79),
       (4, 'QUAD', 'VACANT', 'https://raw.githubusercontent.com/Lokankara/Patterns/main/img/image_130.jpg', 80),
       (2, 'QUEEN', 'VACANT', 'https://raw.githubusercontent.com/Lokankara/Patterns/main/img/image_131.jpg', 81),
       (2, 'KING', 'MAINTENANCE', 'https://raw.githubusercontent.com/Lokankara/Patterns/main/img/image_132.jpg', 82);
