create table if not exists room (
    id        bigserial primary key,
    capacity  integer not null,
    room_type varchar(255),
    constraint room_room_status_check check (room_status in('VACANT','OCCUPIED', 'RESERVED', 'MAINTENANCE')),
    constraint room_room_type_check check (room_type in
                                           ('SINGLE', 'DOUBLE', 'TRIPLE',
                                            'QUAD', 'QUEEN', 'KING', 'TWIN',
                                            'HOLLYWOOD', 'STUDIO', 'CABANA',
                                            'VILLA', 'PENTHOUSES', 'STANDARD',
                                            'DELUXE', 'JOINT', 'CONNECTING',
                                            'SUIT', 'APARTMENT', 'JUNIOR',
                                            'BRIDAL', 'HONEYMOON',
                                            'PRESIDENTIAL', 'ACCESSIBLE'))
);

INSERT INTO room (capacity, room_type, room_status)
VALUES (2, 'SINGLE', 'VACANT'),
       (2, 'DOUBLE', 'OCCUPIED'),
       (3, 'TRIPLE', 'RESERVED'),
       (4, 'QUAD', 'VACANT'),
       (2, 'QUEEN', 'OCCUPIED'),
       (2, 'KING', 'MAINTENANCE'),
       (2, 'TWIN', 'OCCUPIED'),
       (2, 'HOLLYWOOD', 'VACANT'),
       (2, 'STUDIO', 'OCCUPIED'),
       (2, 'CABANA', 'VACANT'),
       (4, 'VILLA', 'OCCUPIED'),
       (2, 'PENTHOUSES', 'VACANT'),
       (2, 'STANDARD', 'MAINTENANCE'),
       (2, 'DELUXE', 'VACANT'),
       (4, 'JOINT', 'VACANT'),
       (4, 'CONNECTING', 'OCCUPIED'),
       (2, 'SUIT', 'VACANT'),
       (2, 'APARTMENT', 'OCCUPIED'),
       (2, 'JUNIOR', 'VACANT'),
       (2, 'BRIDAL', 'VACANT'),
       (2, 'HONEYMOON', 'RESERVED'),
       (2, 'PRESIDENTIAL', 'VACANT'),
       (2, 'ACCESSIBLE', 'VACANT'),
       (2, 'SINGLE', 'OCCUPIED'),
       (2, 'DOUBLE', 'VACANT'),
       (3, 'TRIPLE', 'OCCUPIED');
