name: SonarQube Analysis

on:
    push:
        branches:
            - master
    pull_request:
        types: [ opened, synchronize, reopened ]

jobs:
    sonarqube:
        name: SonarQube
        runs-on: ubuntu-latest

        steps:
            -   name: Checkout code
                uses: actions/checkout@v3
                with:
                    fetch-depth: 0

            -   name: Set up JDK 21
                uses: actions/setup-java@v4
                with:
                    java-version: '21'
                    distribution: 'temurin'
                    cache: maven

            -   name: Build with Maven
                run: mvn -B verify

            -   name: SonarQube Scan
                uses: SonarSource/sonarqube-scan-action@v4
                env:
                    SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
