name: Java Static Code Analysis

on:
    push:
        branches: [ master ]
    pull_request:
        branches: [ master ]

jobs:
    static-code-analysis:
        runs-on: ubuntu-latest

        steps:
            -   name: Checkout code
                uses: actions/checkout@v4

            -   name: Set up JDK 21
                uses: actions/setup-java@v4
                with:
                    distribution: 'temurin'
                    java-version: '21'
                    cache: 'maven'

            -   name: Build with Maven
                run: mvn clean package -DskipTests

            -   name: Run SpotBugs analysis
                run: mvn com.github.spotbugs:spotbugs-maven-plugin:spotbugs

            -   name: Convert SpotBugs XML to SARIF (JSON)
                uses: advanced-security/spotbugs-sarif@v1
                with:
                    spotbugs-xml-path: target/spotbugsXml.xml
                    sarif-output-path: target/spotbugs.sarif

            -   name: Upload SARIF report to GitHub Code Scanning
                uses: github/codeql-action/upload-sarif@v3
                with:
                    sarif_file: target/spotbugs.sarif
