name: Java Static Code Analysis

on:
    push:
        branches:
            - master
    pull_request:
        branches:
            - master

permissions:
    checks: write

jobs:
    static-code-analysis:
        runs-on: ubuntu-latest

        steps:
            -   name: Checkout code
                uses: actions/checkout@v4

            -   name: Setup Java 21
                uses: actions/setup-java@v4
                with:
                    distribution: temurin
                    java-version: 21
                    cache: maven

            -   name: Build with Maven
                run: mvn clean package -DskipTests

            -   name: Run SpotBugs analysis
                run: mvn spotbugs:spotbugs

            -   name: Upload SpotBugs report
                uses: actions/upload-artifact@v4
                with:
                    name: spotbugs-report
                    path: target/spotbugsXml.xml

            -   name: Upload to GitHub Code Scanning
                uses: github/codeql-action/upload-sarif@v2
                with:
                    sarif_file: target/spotbugsXml.xml
